[package]
name = "entity"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "entity"
path = "src/mod.rs"

[dependencies]
serde = "1.0.197"
sea-orm-migration = "1.1.4"

[dependencies.sea-orm]
version = "1.1.0"